### PR TITLE
Add news view

### PR DESCRIPTION
**Pull request by JunyiYang0925**
Add news view that shows news from a news api, and three buttons to switch between views.

### CODE REVIEW

**Comment by Pikkuninja** [comment]
Fixed the merge conflicts as they were kinda trivial. Couple of notes after I quickly went through your code:

- Add IDE files & folders to .gitignore (there's at least the '.idea' folder)
- Name branches after features from now on. Also as this PR has two kinda major things, the tabs and the news view it probably should've been two branches / PRs, but no worries
- Go through the code and compare it with [our bible](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y127), there's things like 'Controller as' syntax, manual DI and passing named functions to angular.module(...).controller instead of anonymous ones

**Comment by Pikkuninja** [comment]
Also please change the tab colors to less bright ones,  currently they kinda burn into your eyes. Simo can probably decide the final colors later on, but you can find some better placeholders from the LLB design guidelines ((https://llb.sis.uta.fi/portal -> tools -> design guidelines).

**Comment by JunyiYang0925** [comment]
Yeah, I also noticed my IDE created a folder, but I didn't remember to use .gitignore. I thought it was supposed to name the branch with person who is working on it, thanks for reminding. I'll go through the bible later this week. The buttons colour I just chose randomly blue/yellow, should be fixed later.

**Comment by antti-TIEA4** [comment]
For indentation it seems your editor is using a mixture of 2 spaces, 4 spaces and sometimes tabs.
Indentation should be 2 spaces.

**Comment by Pikkuninja** [comment]
As discussed in Slack, I checked the code and made a new PR for these features.

**Pull request closed without merging**
